import { AppData, Shortcut } from './types';

const commonCategories = {
  TOOLS: 'Tools',
  FILE: 'File & Edit',
  LAYER: 'Layers',
  VIEW: 'View & Navigation',
  TEXT: 'Typography',
};

// Helper to create IDs
const createId = (app: string, action: string) => `${app}-${action.replace(/\s+/g, '-').toLowerCase()}`;

export const APP_DATA: Record<string, AppData> = {
  ps: {
    id: 'ps',
    name: 'Photoshop',
    color: '#31A8FF',
    icon: 'P',
    shortcuts: [
      // Tools
      { id: 'ps-move', action: 'Move Tool', keys: { win: ['V'], mac: ['V'] }, category: commonCategories.TOOLS },
      { id: 'ps-marquee', action: 'Marquee Tools', keys: { win: ['M'], mac: ['M'] }, category: commonCategories.TOOLS },
      { id: 'ps-lasso', action: 'Lasso Tools', keys: { win: ['L'], mac: ['L'] }, category: commonCategories.TOOLS },
      { id: 'ps-quick-sel', action: 'Quick Selection / Magic Wand', keys: { win: ['W'], mac: ['W'] }, category: commonCategories.TOOLS },
      { id: 'ps-crop', action: 'Crop / Slice Tools', keys: { win: ['C'], mac: ['C'] }, category: commonCategories.TOOLS },
      { id: 'ps-eyedropper', action: 'Eyedropper / Ruler', keys: { win: ['I'], mac: ['I'] }, category: commonCategories.TOOLS },
      { id: 'ps-healing', action: 'Spot Healing / Patch', keys: { win: ['J'], mac: ['J'] }, category: commonCategories.TOOLS },
      { id: 'ps-brush', action: 'Brush / Pencil / Mixer', keys: { win: ['B'], mac: ['B'] }, category: commonCategories.TOOLS },
      { id: 'ps-clone', action: 'Clone / Pattern Stamp', keys: { win: ['S'], mac: ['S'] }, category: commonCategories.TOOLS },
      { id: 'ps-history', action: 'History Brush', keys: { win: ['Y'], mac: ['Y'] }, category: commonCategories.TOOLS },
      { id: 'ps-eraser', action: 'Eraser Tools', keys: { win: ['E'], mac: ['E'] }, category: commonCategories.TOOLS },
      { id: 'ps-gradient', action: 'Gradient / Paint Bucket', keys: { win: ['G'], mac: ['G'] }, category: commonCategories.TOOLS },
      { id: 'ps-dodge', action: 'Dodge / Burn / Sponge', keys: { win: ['O'], mac: ['O'] }, category: commonCategories.TOOLS },
      { id: 'ps-pen', action: 'Pen Tools', keys: { win: ['P'], mac: ['P'] }, category: commonCategories.TOOLS },
      { id: 'ps-type', action: 'Type Tools', keys: { win: ['T'], mac: ['T'] }, category: commonCategories.TOOLS },
      { id: 'ps-path-sel', action: 'Path / Direct Selection', keys: { win: ['A'], mac: ['A'] }, category: commonCategories.TOOLS },
      { id: 'ps-shapes', action: 'Shape Tools', keys: { win: ['U'], mac: ['U'] }, category: commonCategories.TOOLS },
      { id: 'ps-hand', action: 'Hand Tool', keys: { win: ['H'], mac: ['H'] }, category: commonCategories.TOOLS },
      { id: 'ps-rotate-view', action: 'Rotate View Tool', keys: { win: ['R'], mac: ['R'] }, category: commonCategories.TOOLS },
      { id: 'ps-zoom', action: 'Zoom Tool', keys: { win: ['Z'], mac: ['Z'] }, category: commonCategories.TOOLS },
      { id: 'ps-default-colors', action: 'Default Colors', keys: { win: ['D'], mac: ['D'] }, category: commonCategories.TOOLS },
      { id: 'ps-switch-colors', action: 'Switch Colors', keys: { win: ['X'], mac: ['X'] }, category: commonCategories.TOOLS },
      { id: 'ps-quick-mask', action: 'Quick Mask Mode', keys: { win: ['Q'], mac: ['Q'] }, category: commonCategories.TOOLS },
      { id: 'ps-screen-mode', action: 'Change Screen Mode', keys: { win: ['F'], mac: ['F'] }, category: commonCategories.TOOLS },
      { id: 'ps-brush-dec', action: 'Decrease Brush Size', keys: { win: ['['], mac: ['['] }, category: commonCategories.TOOLS },
      { id: 'ps-brush-inc', action: 'Increase Brush Size', keys: { win: [']'], mac: [']'] }, category: commonCategories.TOOLS },
      { id: 'ps-hard-dec', action: 'Decrease Hardness', keys: { win: ['{'], mac: ['{'] }, category: commonCategories.TOOLS },
      { id: 'ps-hard-inc', action: 'Increase Hardness', keys: { win: ['}'], mac: ['}'] }, category: commonCategories.TOOLS },
      { id: 'ps-prev-brush', action: 'Previous Brush', keys: { win: [','], mac: [','] }, category: commonCategories.TOOLS },
      { id: 'ps-next-brush', action: 'Next Brush', keys: { win: ['.'], mac: ['.'] }, category: commonCategories.TOOLS },
      { id: 'ps-first-brush', action: 'First Brush', keys: { win: ['<'], mac: ['<'] }, category: commonCategories.TOOLS },
      { id: 'ps-last-brush', action: 'Last Brush', keys: { win: ['>'], mac: ['>'] }, category: commonCategories.TOOLS },

      // File & Edit
      { id: 'ps-new', action: 'New Document', keys: { win: ['Ctrl', 'N'], mac: ['Cmd', 'N'] }, category: commonCategories.FILE },
      { id: 'ps-open', action: 'Open', keys: { win: ['Ctrl', 'O'], mac: ['Cmd', 'O'] }, category: commonCategories.FILE },
      { id: 'ps-browse', action: 'Browse in Bridge', keys: { win: ['Alt', 'Ctrl', 'O'], mac: ['Opt', 'Cmd', 'O'] }, category: commonCategories.FILE },
      { id: 'ps-close', action: 'Close', keys: { win: ['Ctrl', 'W'], mac: ['Cmd', 'W'] }, category: commonCategories.FILE },
      { id: 'ps-close-all', action: 'Close All', keys: { win: ['Alt', 'Ctrl', 'W'], mac: ['Opt', 'Cmd', 'W'] }, category: commonCategories.FILE },
      { id: 'ps-save', action: 'Save', keys: { win: ['Ctrl', 'S'], mac: ['Cmd', 'S'] }, category: commonCategories.FILE },
      { id: 'ps-save-as', action: 'Save As', keys: { win: ['Shift', 'Ctrl', 'S'], mac: ['Shift', 'Cmd', 'S'] }, category: commonCategories.FILE },
      { id: 'ps-revert', action: 'Revert', keys: { win: ['F12'], mac: ['F12'] }, category: commonCategories.FILE },
      { id: 'ps-print', action: 'Print', keys: { win: ['Ctrl', 'P'], mac: ['Cmd', 'P'] }, category: commonCategories.FILE },
      { id: 'ps-exit', action: 'Exit/Quit', keys: { win: ['Ctrl', 'Q'], mac: ['Cmd', 'Q'] }, category: commonCategories.FILE },
      { id: 'ps-undo', action: 'Undo/Redo', keys: { win: ['Ctrl', 'Z'], mac: ['Cmd', 'Z'] }, category: commonCategories.FILE },
      { id: 'ps-step-fwd', action: 'Step Forward', keys: { win: ['Shift', 'Ctrl', 'Z'], mac: ['Shift', 'Cmd', 'Z'] }, category: commonCategories.FILE },
      { id: 'ps-step-back', action: 'Step Backward', keys: { win: ['Alt', 'Ctrl', 'Z'], mac: ['Opt', 'Cmd', 'Z'] }, category: commonCategories.FILE },
      { id: 'ps-fill', action: 'Fill', keys: { win: ['Shift', 'F5'], mac: ['Shift', 'F5'] }, category: commonCategories.FILE },
      { id: 'ps-free-trans', action: 'Free Transform', keys: { win: ['Ctrl', 'T'], mac: ['Cmd', 'T'] }, category: commonCategories.FILE },
      { id: 'ps-trans-again', action: 'Transform Again', keys: { win: ['Shift', 'Ctrl', 'T'], mac: ['Shift', 'Cmd', 'T'] }, category: commonCategories.FILE },
      { id: 'ps-color-set', action: 'Color Settings', keys: { win: ['Shift', 'Ctrl', 'K'], mac: ['Shift', 'Cmd', 'K'] }, category: commonCategories.FILE },
      { id: 'ps-prefs', action: 'Preferences', keys: { win: ['Ctrl', 'K'], mac: ['Cmd', 'K'] }, category: commonCategories.FILE },
      { id: 'ps-cut', action: 'Cut', keys: { win: ['Ctrl', 'X'], mac: ['Cmd', 'X'] }, category: commonCategories.FILE },
      { id: 'ps-copy', action: 'Copy', keys: { win: ['Ctrl', 'C'], mac: ['Cmd', 'C'] }, category: commonCategories.FILE },
      { id: 'ps-paste', action: 'Paste', keys: { win: ['Ctrl', 'V'], mac: ['Cmd', 'V'] }, category: commonCategories.FILE },
      { id: 'ps-paste-place', action: 'Paste in Place', keys: { win: ['Shift', 'Ctrl', 'V'], mac: ['Shift', 'Cmd', 'V'] }, category: commonCategories.FILE },

      // Layer / Select / Image
      { id: 'ps-levels', action: 'Levels', keys: { win: ['Ctrl', 'L'], mac: ['Cmd', 'L'] }, category: commonCategories.LAYER },
      { id: 'ps-curves', action: 'Curves', keys: { win: ['Ctrl', 'M'], mac: ['Cmd', 'M'] }, category: commonCategories.LAYER },
      { id: 'ps-hue', action: 'Hue/Saturation', keys: { win: ['Ctrl', 'U'], mac: ['Cmd', 'U'] }, category: commonCategories.LAYER },
      { id: 'ps-color-bal', action: 'Color Balance', keys: { win: ['Ctrl', 'B'], mac: ['Cmd', 'B'] }, category: commonCategories.LAYER },
      { id: 'ps-invert', action: 'Invert', keys: { win: ['Ctrl', 'I'], mac: ['Cmd', 'I'] }, category: commonCategories.LAYER },
      { id: 'ps-desaturate', action: 'Desaturate', keys: { win: ['Shift', 'Ctrl', 'U'], mac: ['Shift', 'Cmd', 'U'] }, category: commonCategories.LAYER },
      { id: 'ps-img-size', action: 'Image Size', keys: { win: ['Alt', 'Ctrl', 'I'], mac: ['Opt', 'Cmd', 'I'] }, category: commonCategories.LAYER },
      { id: 'ps-canvas-size', action: 'Canvas Size', keys: { win: ['Alt', 'Ctrl', 'C'], mac: ['Opt', 'Cmd', 'C'] }, category: commonCategories.LAYER },
      { id: 'ps-new-layer', action: 'New Layer', keys: { win: ['Shift', 'Ctrl', 'N'], mac: ['Shift', 'Cmd', 'N'] }, category: commonCategories.LAYER },
      { id: 'ps-layer-copy', action: 'Layer via Copy', keys: { win: ['Ctrl', 'J'], mac: ['Cmd', 'J'] }, category: commonCategories.LAYER },
      { id: 'ps-layer-cut', action: 'Layer via Cut', keys: { win: ['Shift', 'Ctrl', 'J'], mac: ['Shift', 'Cmd', 'J'] }, category: commonCategories.LAYER },
      { id: 'ps-clip-mask', action: 'Create/Release Clipping Mask', keys: { win: ['Alt', 'Ctrl', 'G'], mac: ['Opt', 'Cmd', 'G'] }, category: commonCategories.LAYER },
      { id: 'ps-group', action: 'Group Layers', keys: { win: ['Ctrl', 'G'], mac: ['Cmd', 'G'] }, category: commonCategories.LAYER },
      { id: 'ps-ungroup', action: 'Ungroup Layers', keys: { win: ['Shift', 'Ctrl', 'G'], mac: ['Shift', 'Cmd', 'G'] }, category: commonCategories.LAYER },
      { id: 'ps-merge', action: 'Merge Layers', keys: { win: ['Ctrl', 'E'], mac: ['Cmd', 'E'] }, category: commonCategories.LAYER },
      { id: 'ps-merge-vis', action: 'Merge Visible', keys: { win: ['Shift', 'Ctrl', 'E'], mac: ['Shift', 'Cmd', 'E'] }, category: commonCategories.LAYER },
      { id: 'ps-sel-all', action: 'Select All', keys: { win: ['Ctrl', 'A'], mac: ['Cmd', 'A'] }, category: commonCategories.LAYER },
      { id: 'ps-deselect', action: 'Deselect', keys: { win: ['Ctrl', 'D'], mac: ['Cmd', 'D'] }, category: commonCategories.LAYER },
      { id: 'ps-reselect', action: 'Reselect', keys: { win: ['Shift', 'Ctrl', 'D'], mac: ['Shift', 'Cmd', 'D'] }, category: commonCategories.LAYER },
      { id: 'ps-inv-sel', action: 'Inverse Selection', keys: { win: ['Shift', 'Ctrl', 'I'], mac: ['Shift', 'Cmd', 'I'] }, category: commonCategories.LAYER },
      { id: 'ps-all-layers', action: 'Select All Layers', keys: { win: ['Alt', 'Ctrl', 'A'], mac: ['Opt', 'Cmd', 'A'] }, category: commonCategories.LAYER },
      { id: 'ps-liquify', action: 'Liquify', keys: { win: ['Shift', 'Ctrl', 'X'], mac: ['Shift', 'Cmd', 'X'] }, category: commonCategories.LAYER },
      { id: 'ps-cam-raw', action: 'Camera Raw Filter', keys: { win: ['Shift', 'Ctrl', 'A'], mac: ['Shift', 'Cmd', 'A'] }, category: commonCategories.LAYER },

      // View & Navigation
      { id: 'ps-fit', action: 'Fit to Screen', keys: { win: ['Ctrl', '0'], mac: ['Cmd', '0'] }, category: commonCategories.VIEW },
      { id: 'ps-100', action: '100% Zoom', keys: { win: ['Ctrl', '1'], mac: ['Cmd', '1'] }, category: commonCategories.VIEW },
      { id: 'ps-zoom-in', action: 'Zoom In', keys: { win: ['Ctrl', '='], mac: ['Cmd', '='] }, category: commonCategories.VIEW },
      { id: 'ps-zoom-out', action: 'Zoom Out', keys: { win: ['Ctrl', '-'], mac: ['Cmd', '-'] }, category: commonCategories.VIEW },
      { id: 'ps-extras', action: 'Show/Hide Extras', keys: { win: ['Ctrl', 'H'], mac: ['Cmd', 'H'] }, category: commonCategories.VIEW },
      { id: 'ps-grid', action: 'Show/Hide Grid', keys: { win: ['Ctrl', "'"], mac: ['Cmd', "'"] }, category: commonCategories.VIEW },
      { id: 'ps-guides', action: 'Show/Hide Guides', keys: { win: ['Ctrl', ';'], mac: ['Cmd', ';'] }, category: commonCategories.VIEW },
      { id: 'ps-rulers', action: 'Show/Hide Rulers', keys: { win: ['Ctrl', 'R'], mac: ['Cmd', 'R'] }, category: commonCategories.VIEW },
      { id: 'ps-snap', action: 'Snap', keys: { win: ['Shift', 'Ctrl', ';'], mac: ['Shift', 'Cmd', ';'] }, category: commonCategories.VIEW },
      { id: 'ps-lock-guides', action: 'Lock Guides', keys: { win: ['Alt', 'Ctrl', ';'], mac: ['Opt', 'Cmd', ';'] }, category: commonCategories.VIEW },
      { id: 'ps-panel-layers', action: 'Layers Panel', keys: { win: ['F7'], mac: ['F7'] }, category: commonCategories.VIEW },
      { id: 'ps-panel-color', action: 'Color Panel', keys: { win: ['F6'], mac: ['F6'] }, category: commonCategories.VIEW },
      { id: 'ps-panel-brush', action: 'Brush Panel', keys: { win: ['F5'], mac: ['F5'] }, category: commonCategories.VIEW },
      { id: 'ps-panel-info', action: 'Info Panel', keys: { win: ['F8'], mac: ['F8'] }, category: commonCategories.VIEW },
      { id: 'ps-actions', action: 'Actions Panel', keys: { win: ['Alt', 'F9'], mac: ['Opt', 'F9'] }, category: commonCategories.VIEW },
    ]
  },
  ai: {
    id: 'ai',
    name: 'Illustrator',
    color: '#FF9A00',
    icon: 'A',
    shortcuts: [
      // Tools
      { id: 'ai-select', action: 'Selection Tool', keys: { win: ['V'], mac: ['V'] }, category: commonCategories.TOOLS },
      { id: 'ai-direct', action: 'Direct Selection', keys: { win: ['A'], mac: ['A'] }, category: commonCategories.TOOLS },
      { id: 'ai-magic-wand', action: 'Magic Wand', keys: { win: ['Y'], mac: ['Y'] }, category: commonCategories.TOOLS },
      { id: 'ai-lasso', action: 'Lasso', keys: { win: ['Q'], mac: ['Q'] }, category: commonCategories.TOOLS },
      { id: 'ai-pen', action: 'Pen Tool', keys: { win: ['P'], mac: ['P'] }, category: commonCategories.TOOLS },
      { id: 'ai-curvature', action: 'Curvature Tool', keys: { win: ['Shift', '~'], mac: ['Shift', '~'] }, category: commonCategories.TOOLS },
      { id: 'ai-type', action: 'Type Tool', keys: { win: ['T'], mac: ['T'] }, category: commonCategories.TOOLS },
      { id: 'ai-touch-type', action: 'Touch Type Tool', keys: { win: ['Shift', 'T'], mac: ['Shift', 'T'] }, category: commonCategories.TOOLS },
      { id: 'ai-line', action: 'Line Segment Tool', keys: { win: ['\\'], mac: ['\\'] }, category: commonCategories.TOOLS },
      { id: 'ai-anchor', action: 'Anchor Point Tool', keys: { win: ['Shift', 'C'], mac: ['Shift', 'C'] }, category: commonCategories.TOOLS },
      { id: 'ai-add-anchor', action: 'Add Anchor Point', keys: { win: ['='], mac: ['='] }, category: commonCategories.TOOLS },
      { id: 'ai-del-anchor', action: 'Delete Anchor Point', keys: { win: ['-'], mac: ['-'] }, category: commonCategories.TOOLS },
      { id: 'ai-rect', action: 'Rectangle Tool', keys: { win: ['M'], mac: ['M'] }, category: commonCategories.TOOLS },
      { id: 'ai-ellipse', action: 'Ellipse Tool', keys: { win: ['L'], mac: ['L'] }, category: commonCategories.TOOLS },
      { id: 'ai-brush', action: 'Paintbrush Tool', keys: { win: ['B'], mac: ['B'] }, category: commonCategories.TOOLS },
      { id: 'ai-blob-brush', action: 'Blob Brush Tool', keys: { win: ['Shift', 'B'], mac: ['Shift', 'B'] }, category: commonCategories.TOOLS },
      { id: 'ai-pencil', action: 'Pencil Tool', keys: { win: ['N'], mac: ['N'] }, category: commonCategories.TOOLS },
      { id: 'ai-shaper', action: 'Shaper Tool', keys: { win: ['Shift', 'N'], mac: ['Shift', 'N'] }, category: commonCategories.TOOLS },
      { id: 'ai-scissors', action: 'Scissors Tool', keys: { win: ['C'], mac: ['C'] }, category: commonCategories.TOOLS },
      { id: 'ai-rotate', action: 'Rotate Tool', keys: { win: ['R'], mac: ['R'] }, category: commonCategories.TOOLS },
      { id: 'ai-reflect', action: 'Reflect Tool', keys: { win: ['O'], mac: ['O'] }, category: commonCategories.TOOLS },
      { id: 'ai-transform', action: 'Free Transform Tool', keys: { win: ['E'], mac: ['E'] }, category: commonCategories.TOOLS },
      { id: 'ai-persp-grid', action: 'Perspective Grid Tool', keys: { win: ['Shift', 'P'], mac: ['Shift', 'P'] }, category: commonCategories.TOOLS },
      { id: 'ai-persp-sel', action: 'Perspective Selection Tool', keys: { win: ['Shift', 'V'], mac: ['Shift', 'V'] }, category: commonCategories.TOOLS },
      { id: 'ai-warp', action: 'Warp Tool', keys: { win: ['Shift', 'R'], mac: ['Shift', 'R'] }, category: commonCategories.TOOLS },
      { id: 'ai-width', action: 'Width Tool', keys: { win: ['Shift', 'W'], mac: ['Shift', 'W'] }, category: commonCategories.TOOLS },
      { id: 'ai-eraser', action: 'Eraser Tool', keys: { win: ['Shift', 'E'], mac: ['Shift', 'E'] }, category: commonCategories.TOOLS },
      { id: 'ai-mesh', action: 'Mesh Tool', keys: { win: ['U'], mac: ['U'] }, category: commonCategories.TOOLS },
      { id: 'ai-gradient', action: 'Gradient Tool', keys: { win: ['G'], mac: ['G'] }, category: commonCategories.TOOLS },
      { id: 'ai-eye', action: 'Eyedropper Tool', keys: { win: ['I'], mac: ['I'] }, category: commonCategories.TOOLS },
      { id: 'ai-blend', action: 'Blend Tool', keys: { win: ['W'], mac: ['W'] }, category: commonCategories.TOOLS },
      { id: 'ai-scale', action: 'Scale Tool', keys: { win: ['S'], mac: ['S'] }, category: commonCategories.TOOLS },
      { id: 'ai-graph', action: 'Column Graph Tool', keys: { win: ['J'], mac: ['J'] }, category: commonCategories.TOOLS },
      { id: 'ai-shape-build', action: 'Shape Builder Tool', keys: { win: ['Shift', 'M'], mac: ['Shift', 'M'] }, category: commonCategories.TOOLS },
      { id: 'ai-paint', action: 'Live Paint Bucket', keys: { win: ['K'], mac: ['K'] }, category: commonCategories.TOOLS },
      { id: 'ai-paint-sel', action: 'Live Paint Selection', keys: { win: ['Shift', 'L'], mac: ['Shift', 'L'] }, category: commonCategories.TOOLS },
      { id: 'ai-artboard', action: 'Artboard Tool', keys: { win: ['Shift', 'O'], mac: ['Shift', 'O'] }, category: commonCategories.TOOLS },
      { id: 'ai-slice', action: 'Slice Tool', keys: { win: ['Shift', 'K'], mac: ['Shift', 'K'] }, category: commonCategories.TOOLS },
      { id: 'ai-hand', action: 'Hand Tool', keys: { win: ['H'], mac: ['H'] }, category: commonCategories.TOOLS },
      { id: 'ai-zoom', action: 'Zoom Tool', keys: { win: ['Z'], mac: ['Z'] }, category: commonCategories.TOOLS },
      { id: 'ai-toggle-fill', action: 'Toggle Fill/Stroke', keys: { win: ['X'], mac: ['X'] }, category: commonCategories.TOOLS },
      { id: 'ai-swap-fill', action: 'Swap Fill/Stroke', keys: { win: ['Shift', 'X'], mac: ['Shift', 'X'] }, category: commonCategories.TOOLS },
      { id: 'ai-symbol', action: 'Symbol Sprayer', keys: { win: ['Shift', 'S'], mac: ['Shift', 'S'] }, category: commonCategories.TOOLS },
      { id: 'ai-screen', action: 'Toggle Screen Mode', keys: { win: ['F'], mac: ['F'] }, category: commonCategories.VIEW },
      { id: 'ai-default', action: 'Default Colors', keys: { win: ['D'], mac: ['D'] }, category: commonCategories.TOOLS },
      { id: 'ai-none', action: 'None (Color)', keys: { win: ['/'], mac: ['/'] }, category: commonCategories.TOOLS },

      // File & Edit
      { id: 'ai-new', action: 'Create a Document', keys: { win: ['Ctrl', 'N'], mac: ['Cmd', 'N'] }, category: commonCategories.FILE },
      { id: 'ai-new-tmpl', action: 'Create from Template', keys: { win: ['Shift', 'Ctrl', 'N'], mac: ['Shift', 'Cmd', 'N'] }, category: commonCategories.FILE },
      { id: 'ai-open', action: 'Open Document', keys: { win: ['Ctrl', 'O'], mac: ['Cmd', 'O'] }, category: commonCategories.FILE },
      { id: 'ai-place', action: 'Place File', keys: { win: ['Shift', 'Ctrl', 'P'], mac: ['Shift', 'Cmd', 'P'] }, category: commonCategories.FILE },
      { id: 'ai-exp-scr', action: 'Export for Screens', keys: { win: ['Alt', 'Ctrl', 'E'], mac: ['Opt', 'Cmd', 'E'] }, category: commonCategories.FILE },
      { id: 'ai-save-web', action: 'Save for Web', keys: { win: ['Alt', 'Shift', 'Ctrl', 'S'], mac: ['Opt', 'Shift', 'Cmd', 'S'] }, category: commonCategories.FILE },
      { id: 'ai-package', action: 'Package Document', keys: { win: ['Alt', 'Shift', 'Ctrl', 'P'], mac: ['Opt', 'Shift', 'Cmd', 'P'] }, category: commonCategories.FILE },
      { id: 'ai-file-info', action: 'File Information', keys: { win: ['Alt', 'Shift', 'Ctrl', 'I'], mac: ['Opt', 'Shift', 'Cmd', 'I'] }, category: commonCategories.FILE },
      { id: 'ai-print', action: 'Print', keys: { win: ['Ctrl', 'P'], mac: ['Cmd', 'P'] }, category: commonCategories.FILE },
      { id: 'ai-quit', action: 'Exit Application', keys: { win: ['Ctrl', 'Q'], mac: ['Cmd', 'Q'] }, category: commonCategories.FILE },
      { id: 'ai-color-set', action: 'Color Settings', keys: { win: ['Shift', 'Ctrl', 'K'], mac: ['Shift', 'Cmd', 'K'] }, category: commonCategories.FILE },
      { id: 'ai-prefs', action: 'Preferences', keys: { win: ['Ctrl', 'K'], mac: ['Cmd', 'K'] }, category: commonCategories.FILE },
      { id: 'ai-rep-trans', action: 'Repeat Transform', keys: { win: ['Ctrl', 'D'], mac: ['Cmd', 'D'] }, category: commonCategories.FILE },
      { id: 'ai-move-obj', action: 'Move Object', keys: { win: ['Shift', 'Ctrl', 'M'], mac: ['Shift', 'Cmd', 'M'] }, category: commonCategories.FILE },
      { id: 'ai-group', action: 'Group', keys: { win: ['Ctrl', 'G'], mac: ['Cmd', 'G'] }, category: commonCategories.FILE },
      { id: 'ai-ungroup', action: 'Ungroup', keys: { win: ['Shift', 'Ctrl', 'G'], mac: ['Shift', 'Cmd', 'G'] }, category: commonCategories.FILE },
      { id: 'ai-mask', action: 'Make Clipping Mask', keys: { win: ['Ctrl', '7'], mac: ['Cmd', '7'] }, category: commonCategories.FILE },
      { id: 'ai-sel-art', action: 'Select Artwork in Artboard', keys: { win: ['Ctrl', 'Alt', 'A'], mac: ['Cmd', 'Opt', 'A'] }, category: commonCategories.FILE },
      { id: 'ai-deselect', action: 'Deselect', keys: { win: ['Shift', 'Ctrl', 'A'], mac: ['Shift', 'Cmd', 'A'] }, category: commonCategories.FILE },
      { id: 'ai-reselect', action: 'Reselect', keys: { win: ['Ctrl', '6'], mac: ['Cmd', '6'] }, category: commonCategories.FILE },
      { id: 'ai-sel-above', action: 'Select Object Above', keys: { win: ['Alt', 'Ctrl', ']'], mac: ['Opt', 'Cmd', ']'] }, category: commonCategories.FILE },
      { id: 'ai-sel-below', action: 'Select Object Below', keys: { win: ['Alt', 'Ctrl', '['], mac: ['Opt', 'Cmd', '['] }, category: commonCategories.FILE },
      { id: 'ai-mk-live', action: 'Make Live Paint', keys: { win: ['Alt', 'Ctrl', 'X'], mac: ['Opt', 'Cmd', 'X'] }, category: commonCategories.FILE },

      // View & Navigation
      { id: 'ai-zoom-in', action: 'Zoom In', keys: { win: ['Ctrl', '='], mac: ['Cmd', '='] }, category: commonCategories.VIEW },
      { id: 'ai-zoom-out', action: 'Zoom Out', keys: { win: ['Ctrl', '-'], mac: ['Cmd', '-'] }, category: commonCategories.VIEW },
      { id: 'ai-fit-all', action: 'View All Artboards', keys: { win: ['Ctrl', '0'], mac: ['Cmd', '0'] }, category: commonCategories.VIEW },
      { id: 'ai-rulers', action: 'Show/Hide Rulers', keys: { win: ['Ctrl', 'R'], mac: ['Cmd', 'R'] }, category: commonCategories.VIEW },
      { id: 'ai-smart-guides', action: 'Show/Hide Smart Guides', keys: { win: ['Ctrl', 'U'], mac: ['Cmd', 'U'] }, category: commonCategories.VIEW },
      { id: 'ai-grid', action: 'Show/Hide Grid', keys: { win: ['Ctrl', '\''], mac: ['Cmd', '\''] }, category: commonCategories.VIEW },
      { id: 'ai-align', action: 'Show/Hide Align Panel', keys: { win: ['Shift', 'F7'], mac: ['Shift', 'F7'] }, category: commonCategories.VIEW },
      { id: 'ai-appear', action: 'Show/Hide Appearance', keys: { win: ['Shift', 'F6'], mac: ['Shift', 'F6'] }, category: commonCategories.VIEW },
      { id: 'ai-color-panel', action: 'Show/Hide Color Panel', keys: { win: ['F6'], mac: ['F6'] }, category: commonCategories.VIEW },
      { id: 'ai-gradient-panel', action: 'Show/Hide Gradient Panel', keys: { win: ['Ctrl', 'F9'], mac: ['Cmd', 'F9'] }, category: commonCategories.VIEW },
      { id: 'ai-graphic-styles', action: 'Show/Hide Graphic Styles', keys: { win: ['Shift', 'F5'], mac: ['Shift', 'F5'] }, category: commonCategories.VIEW },
      { id: 'ai-info', action: 'Show/Hide Info Panel', keys: { win: ['Ctrl', 'F8'], mac: ['Cmd', 'F8'] }, category: commonCategories.VIEW },
      { id: 'ai-layers', action: 'Show/Hide Layers Panel', keys: { win: ['F7'], mac: ['F7'] }, category: commonCategories.VIEW },
      { id: 'ai-stroke', action: 'Show/Hide Stroke Panel', keys: { win: ['Ctrl', 'F10'], mac: ['Cmd', 'F10'] }, category: commonCategories.VIEW },
      { id: 'ai-symbols', action: 'Show/Hide Symbols Panel', keys: { win: ['Shift', 'Ctrl', 'F11'], mac: ['Shift', 'Cmd', 'F11'] }, category: commonCategories.VIEW },
      { id: 'ai-transform-panel', action: 'Show/Hide Transform Panel', keys: { win: ['Shift', 'F8'], mac: ['Shift', 'F8'] }, category: commonCategories.VIEW },
      { id: 'ai-pathfinder', action: 'Show/Hide Pathfinder', keys: { win: ['Shift', 'Ctrl', 'F9'], mac: ['Shift', 'Cmd', 'F9'] }, category: commonCategories.VIEW },
      { id: 'ai-outline-view', action: 'Outline View', keys: { win: ['Ctrl', 'Y'], mac: ['Cmd', 'Y'] }, category: commonCategories.VIEW },

      // Text & Layers
      { id: 'ai-char', action: 'Open Character Panel', keys: { win: ['Ctrl', 'T'], mac: ['Cmd', 'T'] }, category: commonCategories.TEXT },
      { id: 'ai-para', action: 'Open Paragraph Panel', keys: { win: ['Alt', 'Ctrl', 'T'], mac: ['Opt', 'Cmd', 'T'] }, category: commonCategories.TEXT },
      { id: 'ai-new-fill', action: 'Add New Fill', keys: { win: ['Ctrl', '/'], mac: ['Cmd', '/'] }, category: commonCategories.LAYER },
      { id: 'ai-add-layer', action: 'Add a Layer', keys: { win: ['Ctrl', 'L'], mac: ['Cmd', 'L'] }, category: commonCategories.LAYER },
      { id: 'ai-add-layer-opt', action: 'Add Layer (Options)', keys: { win: ['Alt', 'Ctrl', 'L'], mac: ['Opt', 'Cmd', 'L'] }, category: commonCategories.LAYER },
    ]
  },
  pr: {
    id: 'pr',
    name: 'Premiere Pro',
    color: '#9999FF',
    icon: 'P',
    shortcuts: [
      // Tools
      { id: 'pr-select', action: 'Selection Tool', keys: { win: ['V'], mac: ['V'] }, category: commonCategories.TOOLS },
      { id: 'pr-razor', action: 'Razor Tool', keys: { win: ['C'], mac: ['C'] }, category: commonCategories.TOOLS },
      { id: 'pr-ripple-tool', action: 'Ripple Edit Tool', keys: { win: ['B'], mac: ['B'] }, category: commonCategories.TOOLS },
      { id: 'pr-insert', action: 'Insert', keys: { win: [','], mac: [','] }, category: commonCategories.TOOLS },
      { id: 'pr-overwrite', action: 'Overwrite', keys: { win: ['.'], mac: ['.'] }, category: commonCategories.TOOLS },
      { id: 'pr-lift', action: 'Lift', keys: { win: [';'], mac: [';'] }, category: commonCategories.TOOLS },
      { id: 'pr-extract', action: 'Extract', keys: { win: ["'"], mac: ["'"] }, category: commonCategories.TOOLS },
      { id: 'pr-snap', action: 'Snap in Timeline', keys: { win: ['S'], mac: ['S'] }, category: commonCategories.TOOLS },
      { id: 'pr-match', action: 'Match Frame', keys: { win: ['F'], mac: ['F'] }, category: commonCategories.TOOLS },
      { id: 'pr-rev-match', action: 'Reverse Match Frame', keys: { win: ['Shift', 'R'], mac: ['Shift', 'R'] }, category: commonCategories.TOOLS },
      { id: 'pr-add-edit', action: 'Add Edit', keys: { win: ['Ctrl', 'K'], mac: ['Cmd', 'K'] }, category: commonCategories.TOOLS },
      { id: 'pr-add-edit-all', action: 'Add Edit to All Tracks', keys: { win: ['Ctrl', 'Shift', 'K'], mac: ['Shift', 'Cmd', 'K'] }, category: commonCategories.TOOLS },
      { id: 'pr-trim', action: 'Trim Edit', keys: { win: ['Shift', 'T'], mac: ['Cmd', 'T'] }, category: commonCategories.TOOLS },
      { id: 'pr-extend', action: 'Extend Edit to Playhead', keys: { win: ['E'], mac: ['E'] }, category: commonCategories.TOOLS },
      { id: 'pr-apply-vid-trans', action: 'Apply Video Transition', keys: { win: ['Ctrl', 'D'], mac: ['Cmd', 'D'] }, category: commonCategories.TOOLS },
      { id: 'pr-apply-aud-trans', action: 'Apply Audio Transition', keys: { win: ['Ctrl', 'Shift', 'D'], mac: ['Shift', 'Cmd', 'D'] }, category: commonCategories.TOOLS },
      { id: 'pr-apply-def-trans', action: 'Apply Default Transitions', keys: { win: ['Shift', 'D'], mac: ['Shift', 'D'] }, category: commonCategories.TOOLS },
      { id: 'pr-subseq', action: 'Make Subsequence', keys: { win: ['Shift', 'U'], mac: ['Cmd', 'U'] }, category: commonCategories.TOOLS },

      // File & Edit
      { id: 'pr-new-proj', action: 'New Project', keys: { win: ['Ctrl', 'Alt', 'N'], mac: ['Opt', 'Cmd', 'N'] }, category: commonCategories.FILE },
      { id: 'pr-new-seq', action: 'New Sequence', keys: { win: ['Ctrl', 'N'], mac: ['Cmd', 'N'] }, category: commonCategories.FILE },
      { id: 'pr-open', action: 'Open Project', keys: { win: ['Ctrl', 'O'], mac: ['Cmd', 'O'] }, category: commonCategories.FILE },
      { id: 'pr-close', action: 'Close', keys: { win: ['Ctrl', 'W'], mac: ['Cmd', 'W'] }, category: commonCategories.FILE },
      { id: 'pr-close-proj', action: 'Close Project', keys: { win: ['Ctrl', 'Shift', 'W'], mac: ['Shift', 'Cmd', 'W'] }, category: commonCategories.FILE },
      { id: 'pr-save', action: 'Save', keys: { win: ['Ctrl', 'S'], mac: ['Cmd', 'S'] }, category: commonCategories.FILE },
      { id: 'pr-save-as', action: 'Save As', keys: { win: ['Ctrl', 'Shift', 'S'], mac: ['Shift', 'Cmd', 'S'] }, category: commonCategories.FILE },
      { id: 'pr-save-copy', action: 'Save a Copy', keys: { win: ['Ctrl', 'Alt', 'S'], mac: ['Opt', 'Cmd', 'S'] }, category: commonCategories.FILE },
      { id: 'pr-import-mb', action: 'Import from Media Browser', keys: { win: ['Ctrl', 'Alt', 'I'], mac: ['Opt', 'Cmd', 'I'] }, category: commonCategories.FILE },
      { id: 'pr-import', action: 'Import', keys: { win: ['Ctrl', 'I'], mac: ['Cmd', 'I'] }, category: commonCategories.FILE },
      { id: 'pr-export', action: 'Export Media', keys: { win: ['Ctrl', 'M'], mac: ['Cmd', 'M'] }, category: commonCategories.FILE },
      { id: 'pr-media-enc', action: 'Send to Media Encoder', keys: { win: ['Alt', 'Shift', 'M'], mac: ['Opt', 'Shift', 'M'] }, category: commonCategories.FILE },
      { id: 'pr-props', action: 'Get Media Properties', keys: { win: ['Ctrl', 'Shift', 'H'], mac: ['Shift', 'Cmd', 'H'] }, category: commonCategories.FILE },
      { id: 'pr-exit', action: 'Exit', keys: { win: ['Ctrl', 'Q'], mac: ['Cmd', 'Q'] }, category: commonCategories.FILE },
      { id: 'pr-undo', action: 'Undo', keys: { win: ['Ctrl', 'Z'], mac: ['Cmd', 'Z'] }, category: commonCategories.FILE },
      { id: 'pr-redo', action: 'Redo', keys: { win: ['Ctrl', 'Shift', 'Z'], mac: ['Shift', 'Cmd', 'Z'] }, category: commonCategories.FILE },
      { id: 'pr-cut', action: 'Cut', keys: { win: ['Ctrl', 'X'], mac: ['Cmd', 'X'] }, category: commonCategories.FILE },
      { id: 'pr-copy', action: 'Copy', keys: { win: ['Ctrl', 'C'], mac: ['Cmd', 'C'] }, category: commonCategories.FILE },
      { id: 'pr-paste', action: 'Paste', keys: { win: ['Ctrl', 'V'], mac: ['Cmd', 'V'] }, category: commonCategories.FILE },
      { id: 'pr-paste-attr', action: 'Paste Attributes', keys: { win: ['Ctrl', 'Alt', 'V'], mac: ['Opt', 'Cmd', 'V'] }, category: commonCategories.FILE },
      { id: 'pr-clear', action: 'Clear', keys: { win: ['Delete'], mac: ['Delete'] }, category: commonCategories.FILE },
      { id: 'pr-ripple-del', action: 'Ripple Delete', keys: { win: ['Shift', 'Delete'], mac: ['Shift', 'Delete'] }, category: commonCategories.FILE },
      { id: 'pr-dup', action: 'Duplicate', keys: { win: ['Ctrl', 'Shift', '/'], mac: ['Shift', 'Cmd', '/'] }, category: commonCategories.FILE },
      { id: 'pr-sel-all', action: 'Select All', keys: { win: ['Ctrl', 'A'], mac: ['Cmd', 'A'] }, category: commonCategories.FILE },
      { id: 'pr-desel-all', action: 'Deselect All', keys: { win: ['Ctrl', 'Shift', 'A'], mac: ['Shift', 'Cmd', 'A'] }, category: commonCategories.FILE },
      { id: 'pr-find', action: 'Find', keys: { win: ['Ctrl', 'F'], mac: ['Cmd', 'F'] }, category: commonCategories.FILE },
      { id: 'pr-edit-orig', action: 'Edit Original', keys: { win: ['Ctrl', 'E'], mac: ['Cmd', 'E'] }, category: commonCategories.FILE },
      { id: 'pr-kb-short', action: 'Keyboard Shortcuts', keys: { win: ['Ctrl', 'Alt', 'K'], mac: ['Cmd', 'Opt', 'K'] }, category: commonCategories.FILE },

      // Clips / Layers
      { id: 'pr-make-sub', action: 'Make Subclip', keys: { win: ['Ctrl', 'U'], mac: ['Cmd', 'U'] }, category: commonCategories.LAYER },
      { id: 'pr-audio-chan', action: 'Audio Channels', keys: { win: ['Shift', 'G'], mac: ['Shift', 'G'] }, category: commonCategories.LAYER },
      { id: 'pr-audio-gain', action: 'Audio Gain', keys: { win: ['G'], mac: ['G'] }, category: commonCategories.LAYER },
      { id: 'pr-speed', action: 'Speed/Duration', keys: { win: ['Ctrl', 'R'], mac: ['Cmd', 'R'] }, category: commonCategories.LAYER },
      { id: 'pr-enable', action: 'Enable Clip', keys: { win: ['Shift', 'E'], mac: ['Shift', 'Cmd', 'E'] }, category: commonCategories.LAYER },
      { id: 'pr-link', action: 'Link/Unlink', keys: { win: ['Ctrl', 'L'], mac: ['Cmd', 'L'] }, category: commonCategories.LAYER },
      { id: 'pr-group', action: 'Group', keys: { win: ['Ctrl', 'G'], mac: ['Cmd', 'G'] }, category: commonCategories.LAYER },
      { id: 'pr-ungroup', action: 'Ungroup', keys: { win: ['Ctrl', 'Shift', 'G'], mac: ['Shift', 'Cmd', 'G'] }, category: commonCategories.LAYER },

      // View & Navigation
      { id: 'pr-render', action: 'Render Effects In to Out', keys: { win: ['Enter'], mac: ['Return'] }, category: commonCategories.VIEW },
      { id: 'pr-mark-in', action: 'Mark In', keys: { win: ['I'], mac: ['I'] }, category: commonCategories.VIEW },
      { id: 'pr-mark-out', action: 'Mark Out', keys: { win: ['O'], mac: ['O'] }, category: commonCategories.VIEW },
      { id: 'pr-mark-clip', action: 'Mark Clip', keys: { win: ['X'], mac: ['X'] }, category: commonCategories.VIEW },
      { id: 'pr-mark-sel', action: 'Mark Selection', keys: { win: ['/'], mac: ['/'] }, category: commonCategories.VIEW },
      { id: 'pr-goto-in', action: 'Go to In', keys: { win: ['Shift', 'I'], mac: ['Shift', 'I'] }, category: commonCategories.VIEW },
      { id: 'pr-goto-out', action: 'Go to Out', keys: { win: ['Shift', 'O'], mac: ['Shift', 'O'] }, category: commonCategories.VIEW },
      { id: 'pr-clear-in', action: 'Clear In', keys: { win: ['Ctrl', 'Shift', 'I'], mac: ['Opt', 'I'] }, category: commonCategories.VIEW },
      { id: 'pr-clear-out', action: 'Clear Out', keys: { win: ['Ctrl', 'Shift', 'O'], mac: ['Opt', 'O'] }, category: commonCategories.VIEW },
      { id: 'pr-clear-io', action: 'Clear In & Out', keys: { win: ['Ctrl', 'Shift', 'X'], mac: ['Opt', 'X'] }, category: commonCategories.VIEW },
      { id: 'pr-add-marker', action: 'Add Marker', keys: { win: ['M'], mac: ['M'] }, category: commonCategories.VIEW },
      { id: 'pr-next-marker', action: 'Go to Next Marker', keys: { win: ['Shift', 'M'], mac: ['Shift', 'M'] }, category: commonCategories.VIEW },
      { id: 'pr-prev-marker', action: 'Go to Previous Marker', keys: { win: ['Ctrl', 'Shift', 'M'], mac: ['Shift', 'Cmd', 'M'] }, category: commonCategories.VIEW },
      { id: 'pr-clear-marker', action: 'Clear Selected Marker', keys: { win: ['Ctrl', 'Alt', 'M'], mac: ['Opt', 'M'] }, category: commonCategories.VIEW },
      { id: 'pr-clear-all-markers', action: 'Clear All Markers', keys: { win: ['Ctrl', 'Alt', 'Shift', 'M'], mac: ['Opt', 'Cmd', 'M'] }, category: commonCategories.VIEW },
      { id: 'pr-zoom-in', action: 'Zoom In', keys: { win: ['='], mac: ['='] }, category: commonCategories.VIEW },
      { id: 'pr-zoom-out', action: 'Zoom Out', keys: { win: ['-'], mac: ['-'] }, category: commonCategories.VIEW },
      { id: 'pr-next-seq', action: 'Next in Sequence', keys: { win: ['Shift', ';'], mac: ['Shift', ';'] }, category: commonCategories.VIEW },
      { id: 'pr-prev-seq', action: 'Previous in Sequence', keys: { win: ['Ctrl', 'Shift', ';'], mac: ['Opt', ';'] }, category: commonCategories.VIEW },
      { id: 'pr-max-frame', action: 'Maximize Frame', keys: { win: ['Shift', '`'], mac: ['Shift', '`'] }, category: commonCategories.VIEW },
      { id: 'pr-loop', action: 'Loop', keys: { win: ['Ctrl', 'L'], mac: ['Cmd', 'L'] }, category: commonCategories.VIEW },
      { id: 'pr-play', action: 'Play/Stop', keys: { win: ['Space'], mac: ['Space'] }, category: commonCategories.VIEW },
      { id: 'pr-step-bk', action: 'Step Backward', keys: { win: ['Left'], mac: ['Left'] }, category: commonCategories.VIEW },
      { id: 'pr-step-fwd', action: 'Step Forward', keys: { win: ['Right'], mac: ['Right'] }, category: commonCategories.VIEW },

      // Text / Graphics
      { id: 'pr-new-text', action: 'New Text Layer', keys: { win: ['Ctrl', 'T'], mac: ['Cmd', 'T'] }, category: commonCategories.TEXT },
      { id: 'pr-new-rect', action: 'New Rectangle', keys: { win: ['Ctrl', 'Alt', 'R'], mac: ['Opt', 'Cmd', 'R'] }, category: commonCategories.TEXT },
      { id: 'pr-new-ell', action: 'New Ellipse', keys: { win: ['Ctrl', 'Alt', 'E'], mac: ['Opt', 'Cmd', 'E'] }, category: commonCategories.TEXT },
      { id: 'pr-bring-front', action: 'Bring to Front', keys: { win: ['Ctrl', 'Shift', ']'], mac: ['Shift', 'Cmd', ']'] }, category: commonCategories.TEXT },
      { id: 'pr-bring-fwd', action: 'Bring Forward', keys: { win: ['Ctrl', ']'], mac: ['Cmd', ']'] }, category: commonCategories.TEXT },
      { id: 'pr-send-back', action: 'Send Backward', keys: { win: ['Ctrl', '['], mac: ['Cmd', '['] }, category: commonCategories.TEXT },
      { id: 'pr-send-back-full', action: 'Send to Back', keys: { win: ['Ctrl', 'Shift', '['], mac: ['Shift', 'Cmd', '['] }, category: commonCategories.TEXT },
      { id: 'pr-sel-next-layer', action: 'Select Next Layer', keys: { win: ['Ctrl', 'Alt', ']'], mac: ['Opt', 'Cmd', ']'] }, category: commonCategories.TEXT },
      { id: 'pr-sel-prev-layer', action: 'Select Prev Layer', keys: { win: ['Ctrl', 'Alt', '['], mac: ['Opt', 'Cmd', '['] }, category: commonCategories.TEXT },
      { id: 'pr-add-cap-track', action: 'Add Caption Track', keys: { win: ['Ctrl', 'Alt', 'A'], mac: ['Opt', 'Cmd', 'A'] }, category: commonCategories.TEXT },
      { id: 'pr-add-cap', action: 'Add Caption', keys: { win: ['Ctrl', 'Alt', 'C'], mac: ['Opt', 'Cmd', 'C'] }, category: commonCategories.TEXT },
      { id: 'pr-next-cap', action: 'Next Caption', keys: { win: ['Ctrl', 'Alt', 'Down'], mac: ['Opt', 'Cmd', 'Down'] }, category: commonCategories.TEXT },
      { id: 'pr-prev-cap', action: 'Previous Caption', keys: { win: ['Ctrl', 'Alt', 'Up'], mac: ['Opt', 'Cmd', 'Up'] }, category: commonCategories.TEXT },
    ]
  },
  ae: {
    id: 'ae',
    name: 'After Effects',
    color: '#9999FF',
    icon: 'A',
    shortcuts: [
      { id: 'ae-pos', action: 'Position', keys: { win: ['P'], mac: ['P'] }, category: commonCategories.LAYER },
      { id: 'ae-scale', action: 'Scale', keys: { win: ['S'], mac: ['S'] }, category: commonCategories.LAYER },
      { id: 'ae-rot', action: 'Rotation', keys: { win: ['R'], mac: ['R'] }, category: commonCategories.LAYER },
      { id: 'ae-opac', action: 'Opacity', keys: { win: ['T'], mac: ['T'] }, category: commonCategories.LAYER },
      { id: 'ae-ram', action: 'RAM Preview', keys: { win: ['0'], mac: ['0'] }, category: commonCategories.VIEW },
      { id: 'ae-comp', action: 'New Composition', keys: { win: ['Ctrl', 'N'], mac: ['Cmd', 'N'] }, category: commonCategories.FILE },
      { id: 'ae-solid', action: 'New Solid', keys: { win: ['Ctrl', 'Y'], mac: ['Cmd', 'Y'] }, category: commonCategories.LAYER },
    ]
  },
  xd: {
    id: 'xd',
    name: 'Adobe XD',
    color: '#FF2BC2',
    icon: 'X',
    shortcuts: [
      { id: 'xd-artboard', action: 'Artboard Tool', keys: { win: ['A'], mac: ['A'] }, category: commonCategories.TOOLS },
      { id: 'xd-rect', action: 'Rectangle', keys: { win: ['R'], mac: ['R'] }, category: commonCategories.TOOLS },
      { id: 'xd-ellipse', action: 'Ellipse', keys: { win: ['E'], mac: ['E'] }, category: commonCategories.TOOLS },
      { id: 'xd-zoom', action: 'Zoom', keys: { win: ['Z'], mac: ['Z'] }, category: commonCategories.VIEW },
      { id: 'xd-grid', action: 'Show/Hide Layout Grid', keys: { win: ['Ctrl', 'Shift', '\''], mac: ['Cmd', 'Shift', '\''] }, category: commonCategories.VIEW },
    ]
  }
};